# Generated by Django 2.1.5 on 2019-01-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogheading', models.CharField(max_length=50)),
                ('blogcontent', models.TextField(max_length=200)),
            ],
        ),
    ]
