# Generated by Django 2.1.5 on 2019-01-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogheading', models.CharField(max_length=255)),
                ('blogtime', models.DateTimeField(auto_now_add=True)),
                ('blogcontent', models.TextField()),
                ('blogimage', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
            ],
        ),
    ]
