# Generated by Django 2.1.5 on 2019-01-12 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogimage',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blogtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blogcontent',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blogheading',
            field=models.CharField(max_length=255),
        ),
    ]
