# Generated by Django 2.1.5 on 2019-01-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190112_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
